$ (function(){
    $('#series1').fadeIn();
    $('#btn1').click(function(){
        $('button').removeClass("active");
        $(this).addClass("active");
        $('#series1').fadeIn();
        $('#series2').hide();
        $('#series3').hide();
        $('#series4').hide(); 
    });
    $('#btn2').click(function(){
        $('button').removeClass("active");
        $(this).addClass("active");
        $('#series1').hide();
        $('#series2').fadeIn();
        $('#series3').hide();
        $('#series4').hide(); 
    });
    $('#btn3').click(function(){
        $('button').removeClass("active");
        $(this).addClass("active");
        $('#series1').hide();
        $('#series2').hide();
        $('#series3').fadeIn();
        $('#series4').hide(); 
    });
    $('#btn4').click(function(){
        $('button').removeClass("active");
        $(this).addClass("active");
        $('#series1').hide();
        $('#series2').hide();
        $('#series3').hide();
        $('#series4').fadeIn(); 
    });
});